/* ==========================================================================
   Build step: bake the public Supabase connection into the app, then package
   the static site into public/ for hosts that want an output directory.

     node tools/build.mjs          (= npm run build)

   Reads SUPABASE_URL and SUPABASE_ANON_KEY from the environment (or a local
   .env file) and writes assets/js/config.local.js, which config.js prefers
   over its empty defaults. Both values are PUBLIC by design - the anon key
   only ever grants what Row Level Security allows - and they end up in the
   JavaScript bundle either way.

   When the variables are absent this writes nothing and the app falls back to
   its in-browser "Connect to Supabase" screen, so a repo clone always works.
   ========================================================================== */

import { readFile, writeFile, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, join } from 'node:path';
import { spawn } from 'node:child_process';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));

async function loadDotEnv() {
  try {
    const text = await readFile(resolve(root, '.env'), 'utf8');
    for (const line of text.split(/\r?\n/)) {
      const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
      if (!m) continue;
      const value = m[2].replace(/^["']|["']$/g, '');
      if (!process.env[m[1]]) process.env[m[1]] = value;
    }
    console.log('  read .env');
  } catch {
    // no .env: rely on the real environment
  }
}

/** Decode the role claim of a JWT-ish key, or null. */
function keyRole(jwt) {
  const parts = jwt.split('.');
  if (parts.length !== 3) return null;
  try {
    return JSON.parse(Buffer.from(parts[1], 'base64').toString('utf8')).role || null;
  } catch {
    return null;
  }
}

async function writeConfig() {
  const url = (process.env.SUPABASE_URL || '').trim().replace(/\/+$/, '');
  const key = (process.env.SUPABASE_ANON_KEY || '').trim();

  if (!url || !key) {
    console.log('  SUPABASE_URL / SUPABASE_ANON_KEY not set -> skipping config.local.js');
    console.log('  the app will show its "Connect to Supabase" screen on first launch');
    return;
  }
  if (!/^https:\/\/.+\.supabase\.(co|in)$/.test(url)) {
    console.warn(`  warning: "${url}" does not look like a Supabase project url`);
  }
  if (key.length < 30) {
    console.log('  SUPABASE_ANON_KEY looks too short -> skipping config.local.js');
    return;
  }
  if (keyRole(key) === 'service_role' || /service_role/.test(key)) {
    console.error('  REFUSING: that is a service_role key. Only the anon/publishable key may ship to browsers.');
    process.exit(1);
  }
  if (keyRole(key) && keyRole(key) !== 'anon') {
    console.warn(`  warning: the key's role claim is "${keyRole(key)}", expected "anon"`);
  }

  const out = `/* Generated by tools/build.mjs - do not edit, do not commit. */
export default {
  supabaseUrl: ${JSON.stringify(url)},
  supabaseAnonKey: ${JSON.stringify(key)},
};
`;
  await writeFile(join(root, 'assets/js/config.local.js'), out, 'utf8');
  console.log(`  wrote assets/js/config.local.js for project ${new URL(url).hostname}`);
}

/** Run the packaging step in-process so `npm run build` is the whole pipeline. */
function pack() {
  return new Promise((done) => {
    const child = spawn(process.execPath, [join(root, 'tools/pack.mjs')], { stdio: 'inherit' });
    child.on('close', (code) => done(code ?? 0));
  });
}

console.log('build:');
await loadDotEnv();
await writeConfig();
console.log('pack:');
const code = await pack();
process.exit(code);
